steps :
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build","-t","gcr.io/$PROJECT_ID/ml-service:$COMMIT_SHA","."]

  - id: "push image to artifact registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push","gcr.io/$PROJECT_ID/ml-service:$COMMIT_SHA"]

  - id: "deploy"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["run","deploy","ml-service","--image","gcr.io/$PROJECT_ID/ml-service:$COMMIT_SHA","--platform","managed","--region","asia-southeast2","--allow-unauthenticated","--port","3000"]